# Generated by Django 5.1.5 on 2025-02-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
