# Generated by Django 5.1.5 on 2025-03-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('processing', 'В работе'), ('delivering', 'В доставке'), ('completed', 'Выполнен'), ('canceled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
