# Generated by Django 5.1.5 on 2025-03-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_report_options_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='canceled_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Отменён (заказы)'),
        ),
        migrations.AddField(
            model_name='report',
            name='canceled_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Отменён (выручка)'),
        ),
        migrations.AddField(
            model_name='report',
            name='completed_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Выполнен (заказы)'),
        ),
        migrations.AddField(
            model_name='report',
            name='completed_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выполнен (выручка)'),
        ),
        migrations.AddField(
            model_name='report',
            name='delivering_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='В доставке (заказы)'),
        ),
        migrations.AddField(
            model_name='report',
            name='delivering_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='В доставке (выручка)'),
        ),
        migrations.AddField(
            model_name='report',
            name='pending_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='В обработке (заказы)'),
        ),
        migrations.AddField(
            model_name='report',
            name='pending_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='В обработке (выручка)'),
        ),
        migrations.AddField(
            model_name='report',
            name='processing_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='В работе (заказы)'),
        ),
        migrations.AddField(
            model_name='report',
            name='processing_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='В работе (выручка)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего заказов'),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая выручка'),
        ),
    ]
